# -*- coding: utf-8 -*-
"""Definitions for thinking-tools theme (business, psychology, self-improvement)."""

DEFINITIONS = [
    {
        "term": "第一原理思考",
        "termEn": "First Principles Thinking",
        "category": "思考フレームワーク",
        "meaning": "既存の常識や慣習をそのまま受け入れず、物事を分解して根本的な事実から再構築する思考法。",
        "example": "「電池は高い」という前提を疑い、材料コストから電気自動車の価格を再計算する。",
    },
    {
        "term": "システム思考",
        "termEn": "Systems Thinking",
        "category": "思考フレームワーク",
        "meaning": "個別の要素ではなく、要素間の関係や全体の構造・フィードバックに注目して物事を捉える考え方。",
        "example": "売上低下を単一要因ではなく、供給・需要・競合・内部プロセスの循環として分析する。",
    },
    {
        "term": "5 Whys",
        "termEn": "5 Whys",
        "category": "問題解決",
        "meaning": "問題の表面的原因に対し「なぜ」を繰り返し問い、根本原因にたどり着く手法。トヨタ生産方式で知られる。",
        "example": "機械が止まった→なぜ？過熱→なぜ？フィルター詰まり→…と掘り下げて真因を特定する。",
    },
    {
        "term": "MECE",
        "termEn": "MECE (Mutually Exclusive, Collectively Exhaustive)",
        "category": "問題解決",
        "meaning": "要素を「重複なく（Mutually Exclusive）」「漏れなく（Collectively Exhaustive）」に分類する整理の原則。",
        "example": "顧客を「新規／既存」ではなく「個人／法人」など、重複のない切り口で分類する。",
    },
    {
        "term": "二次効果思考",
        "termEn": "Second-Order Thinking",
        "category": "意思決定",
        "meaning": "行動の直接的な結果だけでなく、その先に起こる連鎖的な影響まで考慮する思考法。",
        "example": "値下げで売上は増えるが、ブランド価値低下という二次効果も検討する。",
    },
    {
        "term": "反証思考",
        "termEn": "Falsification / Critical Thinking",
        "category": "意思決定",
        "meaning": "自分の仮説や信念が誤りである可能性を積極的に探し、反証できないものだけを信じる姿勢。ポパーの科学哲学に基づく。",
        "example": "新製品が売れると信じる前に、「売れない条件は何か」を列挙して検証する。",
    },
    {
        "term": "OODAループ",
        "termEn": "OODA Loop",
        "category": "意思決定",
        "meaning": "Observe（観察）→ Orient（状況判断）→ Decide（決定）→ Act（行動）のサイクルを素早く回す意思決定モデル。ボイド提唱。",
        "example": "市場変化を観察し、自社の立場を再解釈して、素早く戦略を切り替える。",
    },
    {
        "term": "フェインマンテクニック",
        "termEn": "Feynman Technique",
        "category": "学習法",
        "meaning": "学んだ内容を平易な言葉で他人に説明し、理解の穴を見つけて埋める学習法。物理学者ファインマンにちなむ。",
        "example": "専門用語を使わず小学生にもわかるように説明し、つまずいた点を復習する。",
    },
    {
        "term": "リングルマン効果",
        "termEn": "Ringelmann Effect",
        "category": "組織・心理学",
        "meaning": "グループの人数が増えるほど、1人あたりの作業量（努力）が低下する現象。社会的ローフィングの基礎研究。",
        "example": "綱引きで人数を増やしても、1人あたりの引く力は減少する。",
    },
    {
        "term": "PDCAサイクル",
        "termEn": "PDCA Cycle",
        "category": "問題解決",
        "meaning": "Plan（計画）→ Do（実行）→ Check（評価）→ Act（改善）を繰り返して品質と成果を高める改善サイクル。",
        "example": "施策を小さく試し、結果を測定してから本番展開の計画を修正する。",
    },
    {
        "term": "デザイン思考",
        "termEn": "Design Thinking",
        "category": "思考フレームワーク",
        "meaning": "ユーザーの課題に共感し、発想・試作・検証を反復して革新的な解決策を生み出すアプローチ。",
        "example": "プロトタイプを早期に作り、実際のユーザーに使ってもらって改善する。",
    },
    {
        "term": "リーン思考",
        "termEn": "Lean Thinking",
        "category": "ビジネス",
        "meaning": "価値のないムダを排除し、顧客に価値を届ける流れを最適化する経営・改善の考え方。",
        "example": "在庫や待ち時間を削減し、必要なものを必要なときに届ける。",
    },
    {
        "term": "6つの帽子思考法",
        "termEn": "Six Thinking Hats",
        "category": "思考フレームワーク",
        "meaning": "白（事実）・赤（感情）・黒（批判）・黄（楽観）・緑（創造）・青（プロセス）の6視点を順に切り替えて議論する手法。ド・ボノ提唱。",
        "example": "会議で「今は黒の帽子」と決め、リスクだけに集中して話し合う。",
    },
    {
        "term": "SCAMPER",
        "termEn": "SCAMPER",
        "category": "発想法",
        "meaning": "Substitute（代用）・Combine（結合）・Adapt（応用）・Modify（修正）・Put to other uses（転用）・Eliminate（削除）・Reverse（逆転）の観点でアイデアを広げる技法。",
        "example": "既存製品の「削除（Eliminate）」を検討し、不要な機能を取り除いた新製品を考える。",
    },
    {
        "term": "ロジックツリー",
        "termEn": "Logic Tree",
        "category": "問題解決",
        "meaning": "問題や課題を論理的に分解し、木構造で原因・要因・選択肢を整理する手法。",
        "example": "利益低下を「売上減」と「コスト増」に分け、さらに細かく要因を枝分かれさせる。",
    },
    {
        "term": "アイゼンハワーマトリクス",
        "termEn": "Eisenhower Matrix",
        "category": "生産性",
        "meaning": "タスクを「緊急度」と「重要度」の2軸で4象限に分類し、優先順位を決めるフレームワーク。",
        "example": "重要だが緊急でない「計画・学習」の時間を意識的に確保する。",
    },
    {
        "term": "パレートの法則",
        "termEn": "Pareto Principle (80/20 Rule)",
        "category": "意思決定",
        "meaning": "結果の約80%は原因の約20%によって生じるという経験則。限られた資源を重要な少数に集中させる考え方。",
        "example": "売上の8割を占める顧客2割に営業リソースを集中する。",
    },
    {
        "term": "パーキンソンの法則",
        "termEn": "Parkinson's Law",
        "category": "生産性",
        "meaning": "仕事は与えられた時間いっぱいまで膨張するという法則。期限を短く設定すると効率が上がることがある。",
        "example": "1週間の締切を2日に短縮すると、本質的な作業に集中できる。",
    },
    {
        "term": "機会費用",
        "termEn": "Opportunity Cost",
        "category": "意思決定",
        "meaning": "ある選択をしたときに、選ばなかった最善の代替案から得られなかった利益。",
        "example": "大学進学の機会費用は、その期間に働いて得られたはずの収入。",
    },
    {
        "term": "比較優位",
        "termEn": "Comparative Advantage",
        "category": "意思決定",
        "meaning": "他者と比べて相対的に得意な分野に特化し、取引で全体の利益を最大化する考え方。リカードの貿易理論。",
        "example": "A国は穀物、B国は布を作る方が効率的なら、それぞれ特化して交換する。",
    },
    {
        "term": "SWOT分析",
        "termEn": "SWOT Analysis",
        "category": "ビジネス",
        "meaning": "Strengths（強み）・Weaknesses（弱み）・Opportunities（機会）・Threats（脅威）の4要素で戦略を整理する手法。",
        "example": "自社の強みと市場機会の交点に、新規事業の方向性を置く。",
    },
    {
        "term": "3C分析",
        "termEn": "3C Analysis",
        "category": "ビジネス",
        "meaning": "Customer（顧客）・Competitor（競合）・Company（自社）の3視点で市場と自社の立ち位置を分析するフレームワーク。",
        "example": "顧客ニーズと競合の弱点を照らし合わせ、自社の差別化ポイントを見つける。",
    },
    {
        "term": "ポーターの5フォース",
        "termEn": "Porter's Five Forces",
        "category": "ビジネス",
        "meaning": "業界の競争構造を、新規参入・代替品・買い手・売り手・既存競合の5力で分析するモデル。",
        "example": "参入障壁が低い業界では、価格競争が激化しやすいと判断する。",
    },
    {
        "term": "ブルーオーシャン戦略",
        "termEn": "Blue Ocean Strategy",
        "category": "ビジネス",
        "meaning": "競争の激しい既存市場（レッドオーシャン）ではなく、競争のない新市場（ブルーオーシャン）を創造する戦略。",
        "example": "カラオケ業界が飽和する前に、新しい娯楽の形態を開拓する。",
    },
    {
        "term": "バリューチェーン",
        "termEn": "Value Chain",
        "category": "ビジネス",
        "meaning": "企業活動を原材料調達から販売・サービスまでの一連の価値創造プロセスとして分析する枠組み。ポーター提唱。",
        "example": "物流コストが高い工程を特定し、外注や自動化で競争力を高める。",
    },
    {
        "term": "制約理論",
        "termEn": "Theory of Constraints (TOC)",
        "category": "ビジネス",
        "meaning": "システム全体の成果は最も弱い部分（ボトルネック）によって決まるという考え方。ゴールドラット提唱。",
        "example": "生産ラインの最も遅い工程を改善しない限り、全体のスループットは上がらない。",
    },
    {
        "term": "OKR",
        "termEn": "OKR (Objectives and Key Results)",
        "category": "マネジメント",
        "meaning": "定性的な目標（Objective）と、それを測る定量的な主要結果（Key Results）をセットで管理する目標設定フレームワーク。",
        "example": "Objective「顧客満足度向上」に KR「NPSを40から60へ」を紐づける。",
    },
    {
        "term": "KPI",
        "termEn": "KPI (Key Performance Indicator)",
        "category": "マネジメント",
        "meaning": "組織や個人の目標達成度を測るための重要な業績評価指標。",
        "example": "カスタマーサポート部門のKPIとして初回応答時間を設定する。",
    },
    {
        "term": "SMARTの法則",
        "termEn": "SMART Goals",
        "category": "マネジメント",
        "meaning": "目標をSpecific（具体的）・Measurable（測定可能）・Achievable（達成可能）・Relevant（関連性）・Time-bound（期限付き）にする原則。",
        "example": "「売上を増やす」ではなく「Q3までに新規顧客100社獲得」と設定する。",
    },
    {
        "term": "心理的安全性",
        "termEn": "Psychological Safety",
        "category": "組織・心理学",
        "meaning": "チーム内で失敗や疑問を率直に話しても、罰や排斥を恐れないと感じられる状態。エドモンドソンが研究。",
        "example": "会議で「わかりません」と言っても笑われない文化があるチーム。",
    },
    {
        "term": "ジョハリの窓",
        "termEn": "Johari Window",
        "category": "コミュニケーション",
        "meaning": "自己を「自分が知っている／知らない」×「他者が知っている／知らない」の4領域で整理するモデル。",
        "example": "フィードバックを通じて「盲点（他者のみ知っている領域）」を自分の認識に取り込む。",
    },
    {
        "term": "マズローの欲求階層説",
        "termEn": "Maslow's Hierarchy of Needs",
        "category": "組織・心理学",
        "meaning": "人間の欲求は生理・安全・所属・承認・自己実現の段階的な階層で満たされるという理論。",
        "example": "基本給が不安定なうちは、自己実現より生活の安定が優先される。",
    },
    {
        "term": "ナッジ",
        "termEn": "Nudge",
        "category": "行動科学",
        "meaning": "選択の自由を奪わず、行動のしやすさやデフォルトを変えて望ましい行動を促す介入。",
        "example": "オプトアウト方式の臓器提供登録で、登録率が大幅に上がる。",
    },
    {
        "term": "ダブルループ学習",
        "termEn": "Double-Loop Learning",
        "category": "学習・成長",
        "meaning": "行動の結果を修正するだけでなく、目標や前提・ルールそのものを見直す学習。アージリス提唱。",
        "example": "売上が伸びない原因が「ターゲット顧客の設定そのもの」にあると気づき、戦略を変える。",
    },
    {
        "term": "シングルループ学習",
        "termEn": "Single-Loop Learning",
        "category": "学習・成長",
        "meaning": "目標やルールはそのままに、行動や手段だけを修正して誤差を減らす学習。",
        "example": "目標温度に届かないので、エアコンの設定温度だけを調整する。",
    },
    {
        "term": "成長マインドセット",
        "termEn": "Growth Mindset",
        "category": "学習・成長",
        "meaning": "能力や知性は努力と学習で伸ばせると信じる考え方。デュエックの研究。",
        "example": "失敗を「まだできない」という過程と捉え、練習を続ける。",
    },
    {
        "term": "固定マインドセット",
        "termEn": "Fixed Mindset",
        "category": "学習・成長",
        "meaning": "能力や知性は生まれつき固定されていると信じ、失敗を自分の限界の証拠と捉える考え方。",
        "example": "「数学は向いていない」と決めつけ、挑戦を避ける。",
    },
    {
        "term": "グリット",
        "termEn": "Grit",
        "category": "学習・成長",
        "meaning": "長期目標に向けて情熱と粘り強さを持ち続ける性格特性。ダックワースが研究。",
        "example": "何年も同じ分野で練習を続け、困難があっても目標を諦めない。",
    },
    {
        "term": "フロー状態",
        "termEn": "Flow State",
        "category": "学習・成長",
        "meaning": "挑戦とスキルが釣り合い、没頭して時間を忘れるほど集中できる心理状態。チクセントミハイが提唱。",
        "example": "適度に難しい課題に取り組み、気づけば数時間が経っていた。",
    },
    {
        "term": "深い仕事",
        "termEn": "Deep Work",
        "category": "生産性",
        "meaning": "注意散漫を排し、認知的に高度な作業に長時間集中する働き方。カル・ニューポートが提唱。",
        "example": "通知を切り、2時間ブロックで設計や執筆だけに没頭する。",
    },
    {
        "term": "エッセンシャル思考",
        "termEn": "Essentialism",
        "category": "生産性",
        "meaning": "「より少なく、しかしより良く」—本当に重要な少数に絞り、それ以外を捨てる考え方。",
        "example": "10個のプロジェクトではなく、最もインパクトの大きい2つに集中する。",
    },
    {
        "term": "カイゼン",
        "termEn": "Kaizen",
        "category": "ビジネス",
        "meaning": "小さな改善を継続的に積み重ね、品質と効率を高める日本発の改善思想。",
        "example": "毎週5分の振り返りで、作業手順の小さな無駄を1つずつ除去する。",
    },
    {
        "term": "アジャイル",
        "termEn": "Agile",
        "category": "マネジメント",
        "meaning": "大きな計画に固執せず、短いイテレーションで開発・改善し、変化に柔軟に対応する手法の総称。",
        "example": "2週間ごとに動く製品をリリースし、ユーザーフィードバックで方向修正する。",
    },
    {
        "term": "スクラム",
        "termEn": "Scrum",
        "category": "マネジメント",
        "meaning": "短期のスプリント、日次スタンドアップ、レビューなどを用いるアジャイル開発の代表的フレームワーク。",
        "example": "2週間スプリントの終わりに、完成した機能をデモして次の優先順位を決める。",
    },
    {
        "term": "ラテラルシンキング",
        "termEn": "Lateral Thinking",
        "category": "発想法",
        "meaning": "論理の直線的な延長ではなく、視点をずらして新しい発想を生む思考法。ド・ボノ提唱。",
        "example": "「穴を大きくする」のではなく「穴のない容器」を考える。",
    },
    {
        "term": "水平思考",
        "termEn": "Horizontal Thinking",
        "category": "発想法",
        "meaning": "垂直思考（論理の積み上げ）と対比され、異なる分野や視点を横断的につなげる発想法。ラテラルシンキングと近い。",
        "example": "鳥の羽の構造から飛行機の翼の設計にヒントを得る。",
    },
    {
        "term": "オッカムの剃刀",
        "termEn": "Occam's Razor",
        "category": "意思決定",
        "meaning": "同等に説明できるなら、仮定の数が少ない（より単純な）説明を選ぶべきという原則。",
        "example": "複雑な陰謀論より、シンプルな説明の方が妥当だと判断する。",
    },
    {
        "term": "ハンコックのジレンマ",
        "termEn": "Hancock's Dilemma",
        "category": "意思決定",
        "meaning": "情報が増えるほど判断が遅れ、行動の機会を逃すジレンマ。軍事・危機管理で語られる。",
        "example": "完璧なデータを待っているうちに、競合が先に市場に参入する。",
    },
    {
        "term": "マシュマロテスト",
        "termEn": "Marshmallow Test",
        "category": "行動科学",
        "meaning": "子どもに「今1個か、後で2個か」を選ばせる実験。先延ばし耐性（自己制御）と将来の成果の関連が知られる。",
        "example": "目の前の誘惑に耐え、長期的な利益を選べるかを測る。",
    },
    {
        "term": "ヤーキーズ・ドッドソンの法則",
        "termEn": "Yerkes-Dodson Law",
        "category": "組織・心理学",
        "meaning": "覚醒レベル（緊張・ストレス）とパフォーマンスは逆U字型の関係—適度な緊張が最も良い成果をもたらす。",
        "example": "締切が近すぎるとパニックになり、遠すぎると手を抜いてしまう。",
    },
    {
        "term": "マーフィーの法則",
        "termEn": "Murphy's Law",
        "category": "意思決定",
        "meaning": "「起こりうる最悪のことは起こる」という経験則。リスク管理や冗長設計の動機になる。",
        "example": "プレゼン前に必ずプロジェクターが故障する—と想定してバックアップを用意する。",
    },
    {
        "term": "コンウェイの法則",
        "termEn": "Conway's Law",
        "category": "組織・心理学",
        "meaning": "組織のコミュニケーション構造が、作るシステムの構造を反映するという法則。",
        "example": "3つのチームに分かれていると、3つのモジュールに分かれたソフトができる。",
    },
    {
        "term": "ブルックスの法則",
        "termEn": "Brooks's Law",
        "category": "マネジメント",
        "meaning": "遅れているソフトウェアプロジェクトに人員を追加すると、さらに遅れるという法則。",
        "example": "新人のオンボーディングとコミュニケーションコストが、短期の遅延を悪化させる。",
    },
    {
        "term": "リーナス・ベクナーの法則",
        "termEn": "Linus's Law",
        "category": "マネジメント",
        "meaning": "「十分な目の数があれば、すべてのバグは浅い」と—オープンソースでは参加者が多いほど品質が上がりやすい。",
        "example": "コードレビューに多くの人が関わるほど、欠陥が早く見つかる。",
    },
    {
        "term": "囚人のジレンマ",
        "termEn": "Prisoner's Dilemma",
        "category": "意思決定",
        "meaning": "個人が合理的に行動すると、全体としては非効率な結果になるゲーム理論の典型例。",
        "example": "両社が値下げし合うと、どちらも利益が減るが、単独では値下げしないと不利になる。",
    },
    {
        "term": "コモンズの悲劇",
        "termEn": "Tragedy of the Commons",
        "category": "意思決定",
        "meaning": "共有資源を個人が自己利益のために使い果たすと、全体が枯渇する問題。ハーディンが論じた。",
        "example": "共有牧場に牛を出しすぎると、草地が荒れて誰も使えなくなる。",
    },
    {
        "term": "ナッシュ均衡",
        "termEn": "Nash Equilibrium",
        "category": "意思決定",
        "meaning": "各参加者が他者の戦略を所与として、自分の戦略を変えても得をしない状態。ゲーム理論の基本概念。",
        "example": "両者が現在の価格設定を変えても利益が増えない市場均衡。",
    },
    {
        "term": "プロスペクト理論",
        "termEn": "Prospect Theory",
        "category": "行動科学",
        "meaning": "人は利益と損失を対称に評価せず、損失をより大きく感じ、確実性を過大評価するという意思決定理論。カーネマンとトヴェルスキー。",
        "example": "100万円得する喜びより、100万円失う痛みの方が大きい。",
    },
    {
        "term": "損失回避",
        "termEn": "Loss Aversion",
        "category": "行動科学",
        "meaning": "同等の額でも、得する喜びより失う痛みの方が心理的に大きいという傾向。プロスペクト理論の中核。",
        "example": "1000円の値引きより、1000円の値上げの方が離脱率が高い。",
    },
    {
        "term": "ゲーム理論",
        "termEn": "Game Theory",
        "category": "意思決定",
        "meaning": "複数の意思決定者が互いの行動を考慮して戦略を選ぶ状況を数学的に分析する学問。",
        "example": "入札で相手がどう出すかを予測し、自分の最適入札額を決める。",
    },
    {
        "term": "ウィンウィン",
        "termEn": "Win-Win",
        "category": "コミュニケーション",
        "meaning": "交渉や協力で双方が利益を得る結果を目指す考え方。コヴィーの「7つの習慣」でも重視される。",
        "example": "価格だけでなく納期・品質・長期契約を組み合わせ、双方にメリットを作る。",
    },
    {
        "term": "アイアンの三角形",
        "termEn": "Iron Triangle (Project Management)",
        "category": "マネジメント",
        "meaning": "プロジェクトの「範囲・コスト・スケジュール」は相互に制約し、1つを変えると他が影響を受けるという関係。",
        "example": "納期を短縮するなら、機能を減らすか予算を増やす必要がある。",
    },
    {
        "term": "RACIマトリクス",
        "termEn": "RACI Matrix",
        "category": "マネジメント",
        "meaning": "タスクごとに Responsible（実行）・Accountable（説明責任）・Consulted（相談）・Informed（報告）の役割を明確にする表。",
        "example": "承認者（A）と実作者（R）を分け、責任の曖昧さをなくす。",
    },
    {
        "term": "5S",
        "termEn": "5S",
        "category": "ビジネス",
        "meaning": "整理（Seiri）・整頓（Seiton）・清掃（Seiso）・清潔（Seiketsu）・躾（Shitsuke）の現場改善手法。",
        "example": "不要な書類を捨て、道具に定位置を決め、誰でも同じ場所から取れるようにする。",
    },
    {
        "term": "看板方式",
        "termEn": "Kanban",
        "category": "ビジネス",
        "meaning": "作業の流れを可視化し、仕掛品を抑えて必要な分だけ生産・処理するリーン手法。",
        "example": "カードの枚数で同時進行タスクを制限し、ボトルネックを見える化する。",
    },
    {
        "term": "アブラハム・マズローの自己超越",
        "termEn": "Self-Transcendence (Maslow)",
        "category": "組織・心理学",
        "meaning": "マズローが後年追加した最上位の欲求—自己実現を超え、他者や大いなる目的への奉仕。",
        "example": "個人の成功より、社会課題の解決に人生を捧げる動機。",
    },
    {
        "term": "自己効力感",
        "termEn": "Self-Efficacy",
        "category": "学習・成長",
        "meaning": "自分が特定の課題をうまく遂行できるという信念。バンデューラが提唱。",
        "example": "「練習すればプレゼンが上手くなる」と信じ、挑戦を続ける。",
    },
    {
        "term": "習慣のループ",
        "termEn": "Habit Loop",
        "category": "行動科学",
        "meaning": "きっかけ（Cue）→ ルーティン（Routine）→ 報酬（Reward）の3要素で習慣が形成・維持されるモデル。",
        "example": "コーヒーの香り（きっかけ）→ 喫煙（ルーティン）→ リラックス（報酬）の連鎖を断つ。",
    },
    {
        "term": "WOOP",
        "termEn": "WOOP (Wish, Outcome, Obstacle, Plan)",
        "category": "行動科学",
        "meaning": "願望・結果・障害・計画の4ステップで目標達成を支援するメンタルコントラスト技法。オエッティンゲン提唱。",
        "example": "目標を想像したうえで障害を想定し、「もしXならYする」とif-then計画を立てる。",
    },
    {
        "term": "ポモドーロ・テクニック",
        "termEn": "Pomodoro Technique",
        "category": "生産性",
        "meaning": "25分集中＋5分休憩を繰り返す時間管理技法。長時間の作業を小さな単位に区切る。",
        "example": "タイマーを25分にセットし、鳴るまで1タスクだけに集中する。",
    },
    {
        "term": "GTD",
        "termEn": "GTD (Getting Things Done)",
        "category": "生産性",
        "meaning": "タスクを頭の外に書き出し、次に取るべき行動に分解して処理する生産性システム。アレン・デビッドが提唱。",
        "example": "「企画書」ではなく「企画書の目次を書く」と次の物理的アクションに落とす。",
    },
    {
        "term": "アクティブラーニング",
        "termEn": "Active Learning",
        "category": "学習法",
        "meaning": "一方的な講義ではなく、討論・演習・実践を通じて学習者が能動的に関与する教育・学習の考え方。",
        "example": "講義を聞くだけでなく、ケーススタディで自分の言葉で解決策を述べる。",
    },
    {
        "term": "間隔反復",
        "termEn": "Spaced Repetition",
        "category": "学習法",
        "meaning": "復習の間隔を徐々に空けながら繰り返し、長期記憶への定着を高める学習技法。",
        "example": "1日後・3日後・1週間後に同じ単語を復習するスケジュールを組む。",
    },
    {
        "term": "精緻化",
        "termEn": "Elaboration",
        "category": "学習法",
        "meaning": "新しい情報を既存の知識と結びつけ、具体例や自分の言葉で説明して理解を深める学習戦略。",
        "example": "新しい経済用語を、身近な買い物の例えで説明し直す。",
    },
    {
        "term": "メタ認知",
        "termEn": "Metacognition",
        "category": "学習法",
        "meaning": "自分の思考や学習プロセスについて考える能力。「考えていることを考える」こと。",
        "example": "「この章はまだ理解が浅い」と自覚し、別の教材で補強する。",
    },
    {
        "term": "アブダクション",
        "termEn": "Abductive Reasoning",
        "category": "思考フレームワーク",
        "meaning": "観察された現象から、それを最もよく説明する仮説を推測する推論。ピアスが論じた。",
        "example": "草地が踏み固められている→人が通ったと推測する。",
    },
    {
        "term": "帰納法",
        "termEn": "Inductive Reasoning",
        "category": "思考フレームワーク",
        "meaning": "個別の観察や事例から一般的な法則や結論を導く推論。",
        "example": "観測した100羽のカラスがすべて黒い→「カラスは黒い」と一般化する。",
    },
    {
        "term": "演繹法",
        "termEn": "Deductive Reasoning",
        "category": "思考フレームワーク",
        "meaning": "一般的な前提から、論理的に必然的な結論を導く推論。",
        "example": "「人間は死ぬ。ソクラテスは人間。ゆえにソクラテスは死ぬ。」",
    },
    {
        "term": "仮説駆動",
        "termEn": "Hypothesis-Driven Approach",
        "category": "問題解決",
        "meaning": "データを集めてから考えるのではなく、仮説を先に立て、それを検証する順序で問題に取り組む手法。",
        "example": "「離脱の主因は価格だ」と仮説を立て、アンケートで検証する。",
    },
    {
        "term": "ブレインストーミング",
        "termEn": "Brainstorming",
        "category": "発想法",
        "meaning": "批判を控え、自由に多くのアイデアを出し合う集団発想法。オズボーンが提唱。",
        "example": "「どんな突飛な案でも歓迎」とルールを決め、量を重視してアイデアを書き出す。",
    },
    {
        "term": "マインドマップ",
        "termEn": "Mind Map",
        "category": "発想法",
        "meaning": "中心テーマから枝を伸ばし、関連概念を放射状に視覚化する思考整理ツール。トニー・ブザンが普及。",
        "example": "「新商品企画」を中心に、顧客・機能・価格・チャネルの枝を描く。",
    },
    {
        "term": "KJ法",
        "termEn": "KJ Method (Affinity Diagram)",
        "category": "問題解決",
        "meaning": "川喜田二郎が開発した、発散した意見やデータをグループ化して本質的な構造を見出す整理法。",
        "example": "付箋に書いた顧客の声を似たもの同士でまとめ、課題のクラスタを発見する。",
    },
    {
        "term": "NM法",
        "termEn": "NM Method",
        "category": "発想法",
        "meaning": "川喜田二郎の発想法。キーワードの組み合わせや質問の連鎖で、既成概念にとらわれないアイデアを生む。",
        "example": "「光＋音＋記憶」など無関係な語を結びつけ、新製品のコンセプトを考える。",
    },
    {
        "term": "認知負荷理論",
        "termEn": "Cognitive Load Theory",
        "category": "学習法",
        "meaning": "作業記憶の容量は限られているため、学習材料の複雑さと提示方法を調整すべきという理論。スウェラー提唱。",
        "example": "図と説明を同時に見せすぎず、段階的に情報を与えて理解を助ける。",
    },
    {
        "term": "デルフォイ法",
        "termEn": "Delphi Method",
        "category": "意思決定",
        "meaning": "専門家に複数回アンケートを取り、回答をフィードバックしながら合意に近づける予測・意思決定手法。",
        "example": "将来の技術普及時期について、専門家の意見を匿名で集約し収束させる。",
    },
    {
        "term": "BATNA",
        "termEn": "BATNA (Best Alternative to a Negotiated Agreement)",
        "category": "コミュニケーション",
        "meaning": "交渉が決裂した場合の最善の代替案。交渉力の源泉となる自分の歩み引きラインの根拠。",
        "example": "他社の内定があれば、給与交渉で無理な条件を飲む必要がなくなる。",
    },
    {
        "term": "ハーバーグの法則",
        "termEn": "Hofstadter's Law",
        "category": "生産性",
        "meaning": "「いつも予想より時間がかかる、予想時間を見込んでもさらにかかる」という法則。",
        "example": "2週間で終わると見積もっても、バッファを入れて3週間と計画する。",
    },
    {
        "term": "バーティカル思考",
        "termEn": "Vertical Thinking",
        "category": "発想法",
        "meaning": "論理の筋道に沿って一歩ずつ深掘りし、正しさを積み上げる思考。ラテラルシンキングと対比される。",
        "example": "前提を確認し、因果関係を順に検証して結論に至る。",
    },
    {
        "term": "アンソフのマトリクス",
        "termEn": "Ansoff Matrix",
        "category": "ビジネス",
        "meaning": "既存／新規の製品と市場の組み合わせで成長戦略（浸透・開発・多角化など）を整理するフレームワーク。",
        "example": "既存製品を新しい地域市場に売る「市場開発」を検討する。",
    },
    {
        "term": "BCGマトリクス",
        "termEn": "BCG Matrix",
        "category": "ビジネス",
        "meaning": "事業を市場成長率と相対的市場シェアの2軸で分類し、投資優先度を決めるポートフォリオ分析。",
        "example": "シェアが高く成長も高い「スター」事業に資源を集中する。",
    },
    {
        "term": "サブスティテューション・ゲーム",
        "termEn": "Substitution Game",
        "category": "発想法",
        "meaning": "「Xの代わりにYを使うとどうなるか」を問い、既存の制約から発想を解放する技法。",
        "example": "「会議の代わりにチャットだけで進めたら？」と問い替えて新しい運用を考える。",
    },
]
